services:
  cache:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_volume:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
volumes:
  redis_volume:
